apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: bukmacherski-backend:latest  # Zastąp nazwą swojego obrazu
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: "postgresql://myuser:mypassword@postgres-service/mydatabase"
